apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 3000        # Puerto de servicio
      targetPort: 4000  # Puerto del contenedor
  type: ClusterIP
